# Name of the base branch in GitHub PRs
base_branch: master

# Repos for scanning
repos:
  - magento/devdocs
  - magento/devdocs_internal

# Labels for search
labels:
  - New doc
  - Major update
  - Technical

# output:
#   - markdown
#   - yaml
